addons: 
	sonarcloud:
		organization: "eiderrodriguez"
		token: "83ddb40367ebf69a9d0067bfc1d948fbf626ab66"
	script:
	#the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
	- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco- maven-plugin:report install sonar:sonar